### ISSUE TITLE
Log in

### ISSUE THREAD

**Issue by maomam** [ERNICommunity/erni-ideas-board#1]
As a ERNIan I want to log in into the application to access the data. 

The same procedure as in the visual facilitation app http://visualfacilitation.erni.ch/#/login 

The idea is that the users can use the same login to access the community applications.

**Comment by rapasoft** [comment]
Wouldn't it be easier to use the ERNI domain login name/password? I don't understand why there is a need for a registration page in ERNI internal application (we can just use ActiveDirectory).

**Comment by elgrangrifon45** [comment]
I would strongly prefer using the ERNI Domain...ist simplifies things, not sign-up needed and it's a big step towards an integreated landscape of community-products.

**Comment by maomam** [comment]
As I understood, in visual facilitation it was separate user management because it is much more difficult to use ERNI domain. Does anybody have experience with ERNI domain and active directory? 

We can just reuse the solution in visualfacilitation and that would be a lot easier.

**Comment by rapasoft** [comment]
It is not that difficult, but it would require some enhanced security measures (like SSL and OAuth for REST API). These are not that difficulty as well :D but it might require some formal review. We can start with the simple login/signup mechanism as with the VisualF app, but it would make sense to create some standard that would use the AD authentication (also for future apps).

**Comment by maomam** [comment]
I propose that in context of the EDD we keep it as simple as possible and deal with AD and standards outside of the scope of the day.  Othewise it would just take much time.

**Comment by elgrangrifon45** [comment]
For the Android app, I have a working OAuth2-authenticator at Hand and SSL wouldn't be a Problem. We would spare the sign-up mechanism if we don't Need to have a seperate sign-up form. Additionally we would approch more ERNIans if they don't have to sign-up.

For EDD it would be nice, if the Services could be used without Prior authentication. Like this we can build up some functionality without implementing the whole Login-mechanism first.

**Comment by guslong** [comment]
Agree a common login would be great but we should be careful though about
being dependent on erni IT or having to comply with IT security
requirements.

For example it would be a disaster for usability if the user were required
to log in with a username and password each time. Or God forbid an mTAN and
all the same hassle that goes with logging onto erni connect etc.
